-- =============================================
-- 分类（29 个，对齐 mianshiya.com）
-- =============================================
INSERT INTO category (name, icon, description, sort_order, create_time, update_time) VALUES
('Java 基础', 'icon-java', 'Java 基础面试题，涵盖数据类型、面向对象、集合框架、异常处理等', 1, NOW(), NOW()),
('Java 集合', 'icon-java', 'Java 集合框架面试题，包括 List、Set、Map 底层实现、扩容机制、线程安全等', 2, NOW(), NOW()),
('Java 并发', 'icon-java', 'Java 并发编程面试题，包括线程池、锁机制、AQS、CAS、并发容器等', 3, NOW(), NOW()),
('JVM', 'icon-jvm', 'Java 虚拟机面试题，包括内存模型、垃圾回收、类加载、性能调优等', 4, NOW(), NOW()),
('MySQL', 'icon-mysql', 'MySQL 数据库面试题，包括索引、事务、SQL 优化、锁机制等', 5, NOW(), NOW()),
('Redis', 'icon-redis', 'Redis 缓存面试题，包括数据结构、持久化、集群、分布式锁等', 6, NOW(), NOW()),
('MongoDB', 'icon-mongodb', 'MongoDB 面试题，包括文档模型、聚合管道、分片复制、性能调优等', 7, NOW(), NOW()),
('Spring', 'icon-spring', 'Spring 框架面试题，包括 IoC、AOP、事务管理、Spring MVC 等', 8, NOW(), NOW()),
('SpringBoot', 'icon-spring', 'SpringBoot 面试题，包括自动配置原理、Starter 机制、Actuator、嵌入式容器等', 9, NOW(), NOW()),
('SpringCloud', 'icon-spring', 'SpringCloud 微服务面试题，包括服务注册发现、网关、熔断、配置中心等', 10, NOW(), NOW()),
('MyBatis', 'icon-mybatis', 'MyBatis 持久层框架面试题，包括 SQL 映射、动态 SQL、缓存、插件开发等', 11, NOW(), NOW()),
('Netty', 'icon-netty', 'Netty 网络框架面试题，包括 Reactor 模型、NIO、Channel Pipeline、粘包拆包等', 12, NOW(), NOW()),
('计算机网络', 'icon-network', '计算机网络面试题，包括 TCP/IP、HTTP/HTTPS、DNS、网络安全等', 13, NOW(), NOW()),
('操作系统', 'icon-os', '操作系统面试题，包括进程线程、内存管理、文件系统、死锁等', 14, NOW(), NOW()),
('算法与数据结构', 'icon-algorithm', '算法和数据结构面试题，包括排序、查找、动态规划、树、图等', 15, NOW(), NOW()),
('设计模式', 'icon-design', '设计模式面试题，包括创建型、结构型、行为型模式及应用场景', 16, NOW(), NOW()),
('消息队列', 'icon-mq', '消息队列面试题，包括 Kafka、RabbitMQ、消息可靠性、幂等性等', 17, NOW(), NOW()),
('RabbitMQ', 'icon-rabbitmq', 'RabbitMQ 面试题，包括交换机类型、消息确认、死信队列、高可用等', 18, NOW(), NOW()),
('Kafka', 'icon-kafka', 'Kafka 面试题，包括分区机制、消费者组、高吞吐原理、Exactly-Once 语义等', 19, NOW(), NOW()),
('Nginx', 'icon-nginx', 'Nginx 面试题，包括反向代理、负载均衡、事件驱动模型、SSL 配置等', 20, NOW(), NOW()),
('Docker 与 K8s', 'icon-docker', 'Docker 与 Kubernetes 面试题，包括容器化、镜像构建、Pod、Service、部署策略等', 21, NOW(), NOW()),
('Git', 'icon-git', 'Git 版本控制面试题，包括分支管理、合并策略、工作流、冲突解决等', 22, NOW(), NOW()),
('Linux', 'icon-linux', 'Linux 面试题，包括常用命令、权限管理、Shell 脚本、性能排查等', 23, NOW(), NOW()),
('后端系统设计', 'icon-system', '后端系统设计面试题，包括高并发、分布式架构、分库分表、CAP 理论等', 24, NOW(), NOW()),
('后端场景题', 'icon-scenario', '后端场景面试题，包括秒杀系统、订单处理、支付流程、幂等性设计等', 25, NOW(), NOW()),
('Dubbo', 'icon-dubbo', 'Dubbo 面试题，包括服务注册发现、负载均衡、SPI 扩展、服务治理等', 26, NOW(), NOW()),
('Elasticsearch', 'icon-es', 'Elasticsearch 面试题，包括倒排索引、分词、聚合查询、集群架构等', 27, NOW(), NOW()),
('DevOps', 'icon-devops', 'DevOps 面试题，包括 CI/CD、基础设施即代码、监控告警、自动化运维等', 28, NOW(), NOW()),
('HR 面试', 'icon-hr', 'HR 面试题，包括自我介绍、职业规划、团队协作、压力管理等', 29, NOW(), NOW());

-- =============================================
-- 标签（50 个）
-- =============================================
INSERT INTO tag (name, create_time, update_time) VALUES
('Java', NOW(), NOW()),
('集合', NOW(), NOW()),
('多线程', NOW(), NOW()),
('JVM', NOW(), NOW()),
('索引', NOW(), NOW()),
('事务', NOW(), NOW()),
('缓存', NOW(), NOW()),
('IoC', NOW(), NOW()),
('AOP', NOW(), NOW()),
('分布式', NOW(), NOW()),
('数据结构', NOW(), NOW()),
('算法', NOW(), NOW()),
('Spring', NOW(), NOW()),
('SpringBoot', NOW(), NOW()),
('SpringCloud', NOW(), NOW()),
('微服务', NOW(), NOW()),
('MySQL', NOW(), NOW()),
('Redis', NOW(), NOW()),
('MongoDB', NOW(), NOW()),
('MyBatis', NOW(), NOW()),
('Netty', NOW(), NOW()),
('网络', NOW(), NOW()),
('TCP', NOW(), NOW()),
('HTTP', NOW(), NOW()),
('操作系统', NOW(), NOW()),
('进程', NOW(), NOW()),
('设计模式', NOW(), NOW()),
('消息队列', NOW(), NOW()),
('Kafka', NOW(), NOW()),
('RabbitMQ', NOW(), NOW()),
('Nginx', NOW(), NOW()),
('Docker', NOW(), NOW()),
('Kubernetes', NOW(), NOW()),
('Git', NOW(), NOW()),
('Linux', NOW(), NOW()),
('系统设计', NOW(), NOW()),
('高并发', NOW(), NOW()),
('Dubbo', NOW(), NOW()),
('Elasticsearch', NOW(), NOW()),
('CI/CD', NOW(), NOW()),
('Lambda', NOW(), NOW()),
('Stream', NOW(), NOW()),
('锁', NOW(), NOW()),
('线程池', NOW(), NOW()),
('垃圾回收', NOW(), NOW()),
('内存模型', NOW(), NOW()),
('分库分表', NOW(), NOW()),
('RPC', NOW(), NOW()),
('REST', NOW(), NOW()),
('安全', NOW(), NOW());

-- =============================================
-- 种子题目（5 道手工录入）
-- 更多题目通过 AI 批量生成（BatchGenerationRunner）
-- =============================================
INSERT INTO question (category_id, title, summary, content, principle, comparison, scenario, risk, project_exp, difficulty, view_count, create_time, update_time) VALUES
(1, '说说 Java 中 HashMap 的原理？',
'HashMap 是 Java 最常用的集合之一，基于数组+链表+红黑树实现。',
'## HashMap 原理\n\n### 底层结构\n- JDK 1.7：数组 + 链表\n- JDK 1.8：数组 + 链表 + 红黑树（链表长度 > 8 时转红黑树）\n\n### put 流程\n1. 计算 key 的 hash 值\n2. 对数组长度取模找到桶位置\n3. 如果桶为空，直接放入\n4. 如果桶不为空，遍历链表/红黑树\n   - 如果 key 已存在，覆盖 value\n   - 如果 key 不存在，插入尾部（尾插法）\n5. 插入后检查是否超过阈值，超过则扩容\n\n### 扩容机制\n- 默认初始容量 16，负载因子 0.75\n- 扩容为原来的 2 倍\n- 需要 rehash 重新分配位置',
'### 为什么用红黑树？\n当链表过长时，查找时间复杂度从 O(1) 退化为 O(n)。红黑树保证最坏 O(log n)。\n\n### 为什么负载因子是 0.75？\n空间和时间的权衡。过高（如 1）增加碰撞概率，过低（如 0.5）浪费空间。0.75 是经验值。\n\n### 线程安全性？\nHashMap 非线程安全。JDK 1.7 头插法在多线程扩容时可能形成环形链表导致死循环。JDK 1.8 尾插法避免了此问题，但依然不保证线程安全，并发场景用 ConcurrentHashMap。',
'JDK 1.7 vs 1.8',
'适用于大部分键值对存储场景，非线程安全时首选。缓存场景可选 LinkedHashMap（支持 LRU）。',
'多线程扩容死循环（JDK 1.7）、自定义对象作 key 需正确实现 hashCode 和 equals',
null,
'MEDIUM', 5326, NOW(), NOW()),
(1, 'Java 中的序列化和反序列化是什么？',
'序列化将 Java 对象转字节序列，反序列化将字节序列恢复为对象。',
'## 序列化与反序列化\n\n**序列化**：将 Java 对象转换为字节序列，便于存储或网络传输。\n**反序列化**：将字节序列恢复为 Java 对象。\n\n### 实现方式\n- 实现 `Serializable` 接口\n- 使用 `ObjectOutputStream` / `ObjectInputStream`\n\n### 注意事项\n- 使用 `serialVersionUID` 控制版本兼容性\n- `transient` 关键字标记不需要序列化的字段\n- 静态变量不会被序列化\n- 父类实现了 Serializable，子类自动可序列化',
null,
'Serializable vs Externalizable',
'RPC 远程调用、分布式缓存、Session 持久化、消息队列消息体',
'序列化版本不兼容导致 InvalidClassException、敏感字段未用 transient 泄露',
null,
'EASY', 3350, NOW(), NOW()),
(3, 'Java 中 ConcurrentHashMap 1.7 和 1.8 之间有哪些区别？',
'ConcurrentHashMap 从分段锁升级为 CAS + synchronized，并发性能大幅提升。',
'## ConcurrentHashMap 1.7 vs 1.8\n\n### JDK 1.7\n- **分段锁（Segment）**：继承 ReentrantLock，将数据分为多个 Segment\n- 并发度默认为 16\n- 两次 hash 定位（先找 Segment，再找 Entry）\n\n### JDK 1.8\n- **CAS + synchronized**：放弃了 Segment，直接用 Node 数组\n- 锁粒度更细：只锁链表/红黑树的头节点\n- 引入红黑树优化 hash 冲突\n- 并发度更高，性能更好',
null,
'JDK 1.7 vs 1.8',
'高并发缓存、计数器、高频读写的共享数据结构',
'1.8 中 size() 方法不是精确值（并发累计），但大多数场景可接受',
null,
'MEDIUM', 2908, NOW(), NOW()),
(5, 'MySQL 索引的最左前缀匹配原则是什么？',
'联合索引从最左列开始匹配，遇到范围查询停止。',
'## 最左前缀匹配原则\n\n联合索引 `(a, b, c)` 相当于创建了三个索引：\n- `(a)`\n- `(a, b)`\n- `(a, b, c)`\n\n### 匹配规则\n- 查询条件必须从索引的最左列开始\n- 遇到范围查询（>、<、between、like）会停止匹配\n\n### 示例\n```sql\nWHERE a = 1 AND b = 2 -- 走索引\nWHERE a = 1           -- 走索引\nWHERE b = 2           -- 不走索引（跳过了 a）\nWHERE a = 1 AND c = 3 -- 只用到 a 列索引\n```',
null,
null,
'SQL 查询优化、联合索引设计',
null,
null,
'MEDIUM', 3246, NOW(), NOW()),
(5, 'MySQL 的索引类型有哪些？',
'MySQL 支持 B+Tree、Hash、全文、空间索引四种类型。',
'## MySQL 索引类型\n\n1. **B+Tree 索引**：最常用，支持全值匹配、范围查询、排序\n2. **Hash 索引**：Memory 引擎支持，精确匹配快，不支持范围查询\n3. **全文索引（Full-Text）**：用于大文本字段的模糊搜索\n4. **空间索引（R-Tree）**：MyISAM 引擎支持地理空间数据\n\n### 从功能角度分类\n- 主键索引（PRIMARY）\n- 唯一索引（UNIQUE）\n- 普通索引（INDEX）\n- 联合索引（复合索引）\n- 覆盖索引（Extra 显示 Using index）',
null,
null,
'建表时根据查询模式选择合适的索引类型',
'索引不是越多越好，写操作会维护索引成本',
null,
'EASY', 2941, NOW(), NOW());

-- =============================================
-- 题目-标签关联
-- =============================================
INSERT INTO question_tag (question_id, tag_id) VALUES
(1, 1), (1, 2),
(2, 1),
(3, 1), (3, 3),
(4, 5),
(5, 5);
