SET NAMES utf8mb4;

-- =============================================
-- 分类（46 个，对齐 mianshiya.com /category/hot）
-- =============================================
INSERT INTO category (name, icon, description, sort_order, create_time, update_time) VALUES
('Java 基础', '/icons/java-basics.png', 'Java 基础面试题，涵盖数据类型、面向对象、集合框架、异常处理等', 1, NOW(), NOW()),
('Java 集合', '/icons/java-collections.png', 'Java 集合框架面试题，包括 List、Set、Map 底层实现、扩容机制、线程安全等', 2, NOW(), NOW()),
('Java 并发', '/icons/java-concurrency.png', 'Java 并发编程面试题，包括线程池、锁机制、AQS、CAS、并发容器等', 3, NOW(), NOW()),
('JVM', '/icons/jvm.png', 'Java 虚拟机面试题，包括内存模型、垃圾回收、类加载、性能调优等', 4, NOW(), NOW()),
('MySQL', '/icons/mysql.png', 'MySQL 数据库面试题，包括索引、事务、SQL 优化、锁机制等', 5, NOW(), NOW()),
('Redis', '/icons/redis.png', 'Redis 缓存面试题，包括数据结构、持久化、集群、分布式锁等', 6, NOW(), NOW()),
('MongoDB', '/icons/mongodb.png', 'MongoDB 面试题，包括文档模型、聚合管道、分片复制、性能调优等', 7, NOW(), NOW()),
('Spring', '/icons/spring.png', 'Spring 框架面试题，包括 IoC、AOP、事务管理、Spring MVC 等', 8, NOW(), NOW()),
('SpringBoot', '/icons/spring-boot.png', 'SpringBoot 面试题，包括自动配置原理、Starter 机制、Actuator、嵌入式容器等', 9, NOW(), NOW()),
('SpringCloud', '/icons/spring-cloud.png', 'SpringCloud 微服务面试题，包括服务注册发现、网关、熔断、配置中心等', 10, NOW(), NOW()),
('MyBatis', '/icons/mybatis.png', 'MyBatis 持久层框架面试题，包括 SQL 映射、动态 SQL、缓存、插件开发等', 11, NOW(), NOW()),
('Netty', '/icons/netty.png', 'Netty 网络框架面试题，包括 Reactor 模型、NIO、Channel Pipeline、粘包拆包等', 12, NOW(), NOW()),
('计算机网络', '/icons/computer-network.png', '计算机网络面试题，包括 TCP/IP、HTTP/HTTPS、DNS、网络安全等', 13, NOW(), NOW()),
('操作系统', '/icons/os.png', '操作系统面试题，包括进程线程、内存管理、文件系统、死锁等', 14, NOW(), NOW()),
('算法与数据结构', '/icons/algorithm-data-structure.png', '算法和数据结构面试题，包括排序、查找、动态规划、树、图等', 15, NOW(), NOW()),
('设计模式', '/icons/design-patterns.png', '设计模式面试题，包括创建型、结构型、行为型模式及应用场景', 16, NOW(), NOW()),
('消息队列', '/icons/message-queue.png', '消息队列面试题，包括 Kafka、RabbitMQ、消息可靠性、幂等性等', 17, NOW(), NOW()),
('RabbitMQ', '/icons/rabbitmq.png', 'RabbitMQ 面试题，包括交换机类型、消息确认、死信队列、高可用等', 18, NOW(), NOW()),
('Kafka', '/icons/kafka.png', 'Kafka 面试题，包括分区机制、消费者组、高吞吐原理、Exactly-Once 语义等', 19, NOW(), NOW()),
('Nginx', '/icons/nginx.png', 'Nginx 面试题，包括反向代理、负载均衡、事件驱动模型、SSL 配置等', 20, NOW(), NOW()),
('Docker 与 K8s', '/icons/docker-k8s.png', 'Docker 与 Kubernetes 面试题，包括容器化、镜像构建、Pod、Service、部署策略等', 21, NOW(), NOW()),
('Git', '/icons/git.png', 'Git 版本控制面试题，包括分支管理、合并策略、工作流、冲突解决等', 22, NOW(), NOW()),
('Linux', '/icons/linux.png', 'Linux 面试题，包括常用命令、权限管理、Shell 脚本、性能排查等', 23, NOW(), NOW()),
('后端系统设计', '/icons/system-design.png', '后端系统设计面试题，包括高并发、分布式架构、分库分表、CAP 理论等', 24, NOW(), NOW()),
('后端场景题', '/icons/backend-scenario.png', '后端场景面试题，包括秒杀系统、订单处理、支付流程、幂等性设计等', 25, NOW(), NOW()),
('Dubbo', '/icons/dubbo.png', 'Dubbo 面试题，包括服务注册发现、负载均衡、SPI 扩展、服务治理等', 26, NOW(), NOW()),
('Elasticsearch', '/icons/elasticsearch.png', 'Elasticsearch 面试题，包括倒排索引、分词、聚合查询、集群架构等', 27, NOW(), NOW()),
('DevOps', '/icons/devops.png', 'DevOps 面试题，包括 CI/CD、基础设施即代码、监控告警、自动化运维等', 28, NOW(), NOW()),
('HR 面试', '/icons/hr.png', 'HR 面试题，包括自我介绍、职业规划、团队协作、压力管理等', 29, NOW(), NOW()),
('Go', '/icons/go.png', 'Go 语言面试题，包括基础语法、并发编程、内存管理、标准库等', 30, NOW(), NOW()),
('Python', '/icons/python.png', 'Python 面试题，包括数据类型、面向对象、数据分析、Web 开发等', 31, NOW(), NOW()),
('C++', '/icons/c-plus-plus.png', 'C++ 面试题，包括基础语法、面向对象、STL、并发编程、新特性等', 32, NOW(), NOW()),
('C#', '/icons/c-sharp.png', 'C# 面试题，包括基础语法、.NET 框架、面向对象、并发编程、集合等', 33, NOW(), NOW()),
('PHP', '/icons/php.png', 'PHP 面试题，包括基础语法、面向对象、框架应用、Web 安全等', 34, NOW(), NOW()),
('JavaScript', '/icons/javascript.png', 'JavaScript 面试题，包括 ES6+、异步编程、原型链、闭包、模块化等', 35, NOW(), NOW()),
('TypeScript', '/icons/typescript.png', 'TypeScript 面试题，包括类型系统、泛型、装饰器、工程化配置等', 36, NOW(), NOW()),
('Vue', '/icons/vue.png', 'Vue 面试题，包括响应式原理、组件通信、状态管理、Router、Vue3 等', 37, NOW(), NOW()),
('React', '/icons/react.png', 'React 面试题，包括 Hooks、组件生命周期、状态管理、性能优化等', 38, NOW(), NOW()),
('前端手写代码', '/icons/frontend-handwrite.png', '前端手写代码面试题，包括 Promise 实现、防抖节流、深拷贝、排序算法等', 39, NOW(), NOW()),
('前端代码分析', '/icons/frontend-code-analysis.png', '前端代码分析面试题，包括代码质量、性能分析、内存泄漏、调试技巧等', 40, NOW(), NOW()),
('前端工程化', '/icons/frontend-engineering.png', '前端工程化面试题，包括 Webpack、性能优化、CI/CD、CSS/HTML、场景设计等', 41, NOW(), NOW()),
('AI 大模型', '/icons/ai-llm.png', 'AI 大模型面试题，包括 Transformer、RAG、Agent、Prompt、模型微调等', 42, NOW(), NOW()),
('AI 项目实战', '/icons/ai-project.png', 'AI 项目实战面试题，包括智能体开发、AI 应用平台、模型部署等', 43, NOW(), NOW()),
('系统运维', '/icons/system-ops.png', '系统运维面试题，包括服务器管理、监控告警、日志分析、故障排查等', 44, NOW(), NOW()),
('IT 运维', '/icons/it-ops.png', 'IT 运维面试题，包括网络配置、安全管理、数据备份、系统维护等', 45, NOW(), NOW()),
('OpenClaw', '/icons/openclaw.png', 'OpenClaw 面试题，包括 AI Agent 原理、工具调用、自主规划等', 46, NOW(), NOW());

-- =============================================
-- 标签（50 个）
-- =============================================
INSERT INTO tag (name, create_time, update_time) VALUES
('Java', NOW(), NOW()),
('集合', NOW(), NOW()),
('多线程', NOW(), NOW()),
('JVM', NOW(), NOW()),
('索引', NOW(), NOW()),
('事务', NOW(), NOW()),
('缓存', NOW(), NOW()),
('IoC', NOW(), NOW()),
('AOP', NOW(), NOW()),
('分布式', NOW(), NOW()),
('数据结构', NOW(), NOW()),
('算法', NOW(), NOW()),
('Spring', NOW(), NOW()),
('SpringBoot', NOW(), NOW()),
('SpringCloud', NOW(), NOW()),
('微服务', NOW(), NOW()),
('MySQL', NOW(), NOW()),
('Redis', NOW(), NOW()),
('MongoDB', NOW(), NOW()),
('MyBatis', NOW(), NOW()),
('Netty', NOW(), NOW()),
('网络', NOW(), NOW()),
('TCP', NOW(), NOW()),
('HTTP', NOW(), NOW()),
('操作系统', NOW(), NOW()),
('进程', NOW(), NOW()),
('设计模式', NOW(), NOW()),
('消息队列', NOW(), NOW()),
('Kafka', NOW(), NOW()),
('RabbitMQ', NOW(), NOW()),
('Nginx', NOW(), NOW()),
('Docker', NOW(), NOW()),
('Kubernetes', NOW(), NOW()),
('Git', NOW(), NOW()),
('Linux', NOW(), NOW()),
('系统设计', NOW(), NOW()),
('高并发', NOW(), NOW()),
('Dubbo', NOW(), NOW()),
('Elasticsearch', NOW(), NOW()),
('CI/CD', NOW(), NOW()),
('Lambda', NOW(), NOW()),
('Stream', NOW(), NOW()),
('锁', NOW(), NOW()),
('线程池', NOW(), NOW()),
('垃圾回收', NOW(), NOW()),
('内存模型', NOW(), NOW()),
('分库分表', NOW(), NOW()),
('RPC', NOW(), NOW()),
('REST', NOW(), NOW()),
('安全', NOW(), NOW()),
('Go', NOW(), NOW()),
('Python', NOW(), NOW()),
('C++', NOW(), NOW()),
('C#', NOW(), NOW()),
('PHP', NOW(), NOW()),
('JavaScript', NOW(), NOW()),
('TypeScript', NOW(), NOW()),
('Vue', NOW(), NOW()),
('React', NOW(), NOW()),
('Node.js', NOW(), NOW()),
('Webpack', NOW(), NOW()),
('CSS', NOW(), NOW()),
('HTML', NOW(), NOW()),
('AI', NOW(), NOW()),
('大模型', NOW(), NOW()),
('LLM', NOW(), NOW()),
('RAG', NOW(), NOW()),
('Agent', NOW(), NOW()),
('Prompt', NOW(), NOW()),
('LangChain', NOW(), NOW()),
('OpenClaw', NOW(), NOW()),
('运维', NOW(), NOW()),
('监控', NOW(), NOW());

-- 题目数据通过 fetch-questions.js 生成
-- 初始化数据库请使用: mysql -u root -p lcb_interview < backend/scripts/sql/init.sql
-- init.sql 包含: 建表 + 分类 + 标签 + 6386道DRAFT题目（一站式导入）
